version: "3.9"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: ray
      N8N_BASIC_AUTH_PASSWORD: 1ray2ray
      TZ: America/Sao_Paulo
    volumes:
      - ./n8n_data:/home/node/.n8n
